### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by elisewalsh** [elisewalsh/organicdyes#1]
- [ ] Work on content
- [ ] Tints, and subcategories
- [ ] Intro section to help minimize paragraph length
- [ ] Repeating the title background color in other parts of the page
- [ ] Paragraph text size, make smaller
